name: Docker Image CI

on:
  push:
    branches:
      - master

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  IMAGE_NAME: sebbia/postgres-proxy

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Docker Hub description
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASSWORD}}
          slug: sebbia/postgres-proxy
          readme: ./README.md
          description: true

  build-latest:
    runs-on: ubuntu-latest
    env:
      TAG: "latest"
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${IMAGE_NAME}:${TAG}
      - name: Push image to Docker Hub
        run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
          docker push ${IMAGE_NAME}:${TAG}
